import type { Metadata } from "next";
import "./globals.css";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const TITLE = "Atmos — check in on earth once in a while";
const DESCRIPTION =
  "Check in on earth once in a while — a live, playful weather visualization of cities around the world, powered by Open-Meteo.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: "Atmos",
    type: "website",
    // The actual image is generated by app/opengraph-image.tsx (Next.js
    // picks it up automatically via file convention) — no need to list it here.
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden antialiased">
      <body className="h-full overflow-hidden flex flex-col font-sans">{children}</body>
    </html>
  );
}
